import './SidePanel.css';
import PredeployedAccounts from '../components/predeployedAccounts/predeployedAccounts';
import DockerCommandGenerator from '../components/dockerCommand/dockerCommand';

export const SidePanel = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext';

  return (
    <main>
      <h3>SidePanel Page</h3>
      <DockerCommandGenerator />
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <PredeployedAccounts />
    </main>
  );
};

export default SidePanel;
